# Generated by Django 4.2 on 2023-04-21 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('currentDate', models.DateField(auto_now=True)),
                ('completionDate', models.DateField()),
                ('goalCategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
