# Generated by Django 4.2 on 2023-04-23 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goalCategory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
