# Generated by Django 4.2 on 2023-04-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_goal_goalcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goalCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='goalsInCategory',
            field=models.ManyToManyField(to='api.goal'),
        ),
    ]
