# Generated by Django 4.2 on 2023-04-25 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_goal_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[('next up', 0), ('In Progress', 1), ('Complete', 2), ('Archive', 3)], null=True)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.goal')),
                ('solution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.solution')),
            ],
        ),
    ]
