# Generated by Django 4.2 on 2023-04-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_journal_date_task_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='goalsInCategory',
            field=models.ManyToManyField(to='api.goal'),
        ),
        migrations.AlterField(
            model_name='category',
            name='journalsInCategory',
            field=models.ManyToManyField(to='api.journal'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tasksInCategory',
            field=models.ManyToManyField(to='api.task'),
        ),
    ]
