# Generated by Django 4.2 on 2023-04-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_category_goalsincategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='goal',
        ),
    ]
