# Generated by Django 4.2 on 2023-04-25 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_task_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solution'),
        ),
    ]
