# Generated by Django 4.2 on 2023-04-29 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_task_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='journalsInCategory',
        ),
    ]
