# Generated by Django 4.2 on 2023-04-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_category_journalsincategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tasksInCategory',
        ),
    ]
