# Generated by Django 4.2 on 2023-04-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_category_tasksincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tasksInCategory',
            field=models.ManyToManyField(to='api.task'),
        ),
    ]
